/*
 * This source file was generated by the Gradle 'init' task
 */
package io.miti;

public class App {
    public static void main(String[] args) {
        final App app = new App();
        MProfiler.reset();
        app.doStuff();
        MProfiler.stop(true);
    }

    private void sleep() {
        try {
            Thread.sleep(50L);
        } catch (InterruptedException e) {
            System.out.println(LoggingUtils.getExceptionSummary(e));
        }
    }

    private void doStuff() {
        MProfiler.start("doStuff");
        for (int i = 0; i < 10; i++) {
            MProfiler.start("Sleeping-1");
            sleep();
            for (int i1 = 0; i1 < 10; i1++) {
                MProfiler.start("Sleeping-2");
                sleep();
                MProfiler.stop();
            }
            MProfiler.stop();
        }
    }
}
